Changement de l'affichage du sex
Prakkkmak/animaliste-front pull request #37
Opened 2021-01-16 14:54 UTC by BastienLamour

Modification de l'affichage du sex dans le détail de l'animal

2021-01-16 14:54 UTC, BastienLamour commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mauvais affichage du sexe](https://trello.com/c/EpchcCZt/105-mauvais-affichage-du-sexe)

2021-01-16 21:09 UTC, Prakkkmak requested changes
Je suis contre ce changement. AnimalField ne doit pas contenir de métier et une vue spéciale devrais exister pour le sexe à mon humble avis. Beacoup de champs auront un comportement particulier.
Ce qui peux etre fait c'est que les lignes 7 et 8 représentent une vue. 
La vue générale (qui affiche juste un string) sera celle par défaut et d'autres vues prendront le relais pour le sexe etc. Je pense même qu'on peux mettre une vue en parametre (props) de AnimalField. 
En tout cas AnimalField ne devrait jamais avoir de métier à l'interieur

2021-01-16 23:53 UTC, BastienLamour commented
Je ne sais pas trop si c'est pertinent de mettre en place une vue pour changer l'affichage d'une donnée.

Pour moi une vue, avec son template, créer quelque chose de générique qui va être utiliser plus d'une fois dans l'application. Ici la vue AnimalField qui permet d'afficher les champs du document reçu va donc être utiliser autant de fois qu'on a de champs pour un animal.
Certes les vues permettent de séparer des actions spécifiques mais faire une vue pour chaque action spécifique de notre application est, je pense, allez trop loin dans cette partie de la conception. 
Donc je ne pense pas que faire une vue seulement changer la valeur `true` / `false` en "Mâle" / "Femelle" ou quelque soit le changement d'affichage qu'on veut pour une donnée.
Pour moi c'est donc bien dans cette vue `AnimalField` que l'on doit faire les transformations "métier" / "front" des données, car c'est dans la vue "au dessus" qu'on va traiter la réception / l'envoie vers le back, on a donc une bonne hiérarchie entre les vues.

Désolé pour le roman mdrr mais comme ça j'ai pu étaler ce que je comprends et tu pourras me dire si c'est de la merde ou pas :grin:.
Hésite pas à me dire si je m'exprime mal aussi, j'ai du mal à expliquer ce que j'ai en tête souvent.

2021-01-17 22:17 UTC, Prakkkmak commented
> Je ne sais pas trop si c'est pertinent de mettre en place une vue pour changer l'affichage d'une donnée spécifique.
> 
> Pour moi une vue, avec son template, créer quelque chose de générique qui va être utiliser plus d'une fois dans l'application. Ici la vue AnimalField qui permet d'afficher les champs du document reçu va donc être utiliser autant de fois qu'on a de champs pour un animal.
> Certes les vues permettent de séparer des actions spécifiques mais faire une vue pour chaque action spécifique de notre application est, je pense, allez trop loin dans cette partie de la conception.
> Donc je ne pense pas que faire une vue seulement changer la valeur `true` / `false` en "Mâle" / "Femelle" ou quelque soit le changement d'affichage qu'on veut pour une donnée.
> Pour moi c'est donc bien dans cette vue `AnimalField` que l'on doit faire les transformations "métier" / "front" des données, car c'est dans la vue "au dessus" qu'on va traiter la réception / l'envoie vers le back, on a donc une bonne hiérarchie entre les vues.
> 
> Désolé pour le roman mdrr mais comme ça j'ai pu étaler ce que je comprends et tu pourras me dire si c'est de la merde ou pas 😁.
> Hésite pas à me dire si je m'exprime mal aussi, j'ai du mal à expliquer ma vision des choses souvent.

Le problème c'est que tu "bloques" l'état de la vue je pense. C'est a dire que la, la vue n'est plus juste un champ mais un champ ou un champ spécifique. C'est comme ne Java tu ne met pas de code spécifique dans la classe parent, c'est un code smell. Quand on aura 50 types de données nous n'allons pas mettre 50 v-if. Surtout que si on change la clé ce sera un bordel sans nom etc .. 
Je pense vraiment que Field.vue devrait avoir une autre vue en parametre optionnel qui est le champ spécifique sous forme de vue. Comme ca un AnimalField.vue c'est un champ et on peux le parametrer avec par exemple un AnimalSexField.vue

2021-01-23 16:46 UTC, BastienLamour commented
/!\ ne surtout pas merge : 
erreur rencontrée : `[Vue warn]: Invalid VNode type: undefined (undefined) `

aides utilisées :
-  https://v3.vuejs.org/guide/component-dynamic-async.html#dynamic-components-with-keep-alive
- https://v3.vuejs.org/api/built-in-components.html#component

2021-01-30 11:10 UTC, Prakkkmak commented on src/components/animal/form/AnimalFieldDisplayDefault.vue
> +  props: ['data', 'edit'],
Manque emits

2021-01-30 11:10 UTC, Prakkkmak commented on src/components/animal/form/AnimalFieldDisplaySex.vue
> +  props: ['data', 'edit'],
manque emits

2021-01-30 11:11 UTC, Prakkkmak commented on src/components/animal/form/AnimalFieldDisplayDefault.vue
> +  props: ['data', 'edit'],
```suggestion
  props: ['data', 'edit'],
  emits: ['update'],
```

2021-01-30 11:11 UTC, Prakkkmak commented on src/components/animal/form/AnimalFieldDisplaySex.vue
> +  props: ['data', 'edit'],
```suggestion
  props: ['data', 'edit'],
  emits: ['update'],
```

2021-01-30 11:12 UTC, Prakkkmak approved these changes

2021-01-30 14:00 UTC, merged