Ajout d'un header et d'un footer
Prakkkmak/animaliste-front pull request #65
Opened 2021-02-05 18:12 UTC by BastienLamour

2021-02-05 18:12 UTC, BastienLamour commented
![](https://github.trello.services/images/mini-trello-icon.png) [Beautification](https://trello.com/c/6pTreXOU/85-beautification)

2021-02-05 20:49 UTC, Prakkkmak requested changes

2021-02-05 20:49 UTC, Prakkkmak commented on src/App.vue
> +    <a href="https://github.com/Prakkkmak">Prakkkmak</a>. /Licence code &
Met pas la license et met ton nom et ton github

2021-02-05 20:49 UTC, Prakkkmak commented on src/App.vue
> +  <section class="hero is-primary">
Photo a mettre ( baniere )

2021-02-06 18:32 UTC, Prakkkmak approved these changes

2021-02-06 18:32 UTC, merged